#!/bin/bash
pwd
echo "#####################"
ls -al
echo "#####################"
cd /app
# ./proxy http -m -p :$PORT -t ws --local-ws-password 020Sdu*#*
./proxy http -m -t kcp -p :22852 --kcp-key 020Sdu*#*
